CREATE TABLE students (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR(20)  NOT NULL,
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_students_student_code UNIQUE (student_code)
);

CREATE INDEX idx_students_last_name ON students (last_name);
