-- "Class" in the domain; named "course" in code because Class is a Java core type.
CREATE TABLE courses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)   NOT NULL,
    title       VARCHAR(150)  NOT NULL,
    description VARCHAR(1000),
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uk_courses_code UNIQUE (code)
);
