-- Many-to-many between students and courses, as an explicit table so it can carry
-- enrolled_at and so duplicates are rejected by the database itself.
CREATE TABLE enrollments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id  BIGINT      NOT NULL REFERENCES students (id) ON DELETE CASCADE,
    course_id   BIGINT      NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_enrollments_student_course UNIQUE (student_id, course_id)
);

-- The unique constraint already indexes lookups by student_id (leading column);
-- this one serves "students of a class".
CREATE INDEX idx_enrollments_course_id ON enrollments (course_id);
